; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Flutter Ruffle"
#define MyAppEngName "Flutter Ruffle"
#define MyAppVersion "1.2.0"
#define MyAppPublisher "lycstar"
#define MyAppURL "https://github.com/lycstar/flutter_ruffle"
#define MyAppExeName "flutter_ruffle.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=A6A40E4D-8E48-4FC0-8B3C-FA7E74E0E5C1
AppName={cm:AppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf64}\{#MyAppEngName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=.
OutputBaseFilename=flutter_ruffle-windows-x64-setup-{#MyAppVersion}
SetupIconFile={#SourcePath}\windows\runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
VersionInfoProductName={cm:AppName}
VersionInfoDescription={cm:AppName}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
#ifexist "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseTraditional.isl"
Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"
#endif
#ifexist "C:\Program Files\Inno Setup 6\Languages\ChineseTraditional.isl"
Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"
#endif
#ifexist "C:\Program Files (x86)\Inno Setup 6\Languages\Japanese.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
#endif
#ifexist "C:\Program Files (x86)\Inno Setup 6\Languages\Korean.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
#endif

[CustomMessages]
english.AppName=Flutter Ruffle
chinesesimplified.AppName=Flutter Ruffle
#ifexist "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseTraditional.isl"
chinesetraditional.AppName=Flutter Ruffle
#endif
#ifexist "C:\Program Files\Inno Setup 6\Languages\ChineseTraditional.isl"
chinesetraditional.AppName=Flutter Ruffle
#endif
#ifexist "C:\Program Files (x86)\Inno Setup 6\Languages\Japanese.isl"
japanese.AppName=Flutter Ruffle
#endif
#ifexist "C:\Program Files (x86)\Inno Setup 6\Languages\Korean.isl"
korean.AppName=Flutter Ruffle
#endif

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
Source: "{#SourcePath}\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourcePath}\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{cm:AppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{cm:AppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{cm:AppName}}"; Flags: nowait postinstall skipifsilent
