// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `logical_key_from_str`, `mouse_button_from_u8`, `physical_key_from_str`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 设置 player 的画质（可用值：low/medium/high/best/8x8/8x8linear/16x16/16x16linear）。
void playerSetQuality({required BigInt playerId, required String quality}) =>
    RustLib.instance.api.crateApiCorePlayerSetQuality(
      playerId: playerId,
      quality: quality,
    );

/// 获取 player 当前画质（返回值同 Stage.quality：low/medium/high/best/8x8/...；对应 ruffle_core::Player::quality）。
String playerQuality({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerQuality(playerId: playerId);

/// 获取 player 是否处于播放状态（对应 ruffle_core::Player::is_playing）。
bool playerIsPlaying({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerIsPlaying(playerId: playerId);

/// 设置 player 播放状态（对应 ruffle_core::Player::set_is_playing）。
void playerSetIsPlaying({required BigInt playerId, required bool isPlaying}) =>
    RustLib.instance.api.crateApiCorePlayerSetIsPlaying(
      playerId: playerId,
      isPlaying: isPlaying,
    );

/// 获取 player 主音量（范围通常为 0.0~1.0，对应 ruffle_core::Player::volume）。
double playerVolume({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerVolume(playerId: playerId);

/// 设置 player 主音量（范围通常为 0.0~1.0，对应 ruffle_core::Player::set_volume）。
void playerSetVolume({required BigInt playerId, required double volume}) =>
    RustLib.instance.api.crateApiCorePlayerSetVolume(
      playerId: playerId,
      volume: volume,
    );

/// 获取 player 是否为全屏状态（对应 ruffle_core::Player::is_fullscreen）。
bool playerIsFullscreen({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerIsFullscreen(playerId: playerId);

/// 设置 player 全屏状态（对应 ruffle_core::Player::set_fullscreen）。
void playerSetFullscreen({
  required BigInt playerId,
  required bool isFullscreen,
}) => RustLib.instance.api.crateApiCorePlayerSetFullscreen(
  playerId: playerId,
  isFullscreen: isFullscreen,
);

/// 设置是否允许 SWF 进入全屏（对应 ruffle_core::Player::set_allow_fullscreen）。
void playerSetAllowFullscreen({
  required BigInt playerId,
  required bool allowFullscreen,
}) => RustLib.instance.api.crateApiCorePlayerSetAllowFullscreen(
  playerId: playerId,
  allowFullscreen: allowFullscreen,
);

/// 获取 letterbox 配置（off/fullscreen/on，对应 ruffle_core::Player::letterbox）。
String playerLetterbox({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerLetterbox(playerId: playerId);

/// 设置 letterbox 配置（off/fullscreen/on，对应 ruffle_core::Player::set_letterbox）。
void playerSetLetterbox({
  required BigInt playerId,
  required String letterbox,
}) => RustLib.instance.api.crateApiCorePlayerSetLetterbox(
  playerId: playerId,
  letterbox: letterbox,
);

/// 获取舞台背景色（AARRGGBB），None 表示使用 SWF 默认背景（对应 ruffle_core::Player::background_color）。
int? playerBackgroundColor({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerBackgroundColor(playerId: playerId);

/// 设置舞台背景色（AARRGGBB），None 表示清空并回退到 SWF 默认背景（对应 ruffle_core::Player::set_background_color）。
void playerSetBackgroundColor({required BigInt playerId, int? argb}) => RustLib
    .instance
    .api
    .crateApiCorePlayerSetBackgroundColor(playerId: playerId, argb: argb);

/// 获取当前 movie 的 frame rate（FPS，对应 ruffle_core::Player::frame_rate）。
double playerFrameRate({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerFrameRate(playerId: playerId);

/// 获取主时间轴当前帧（1-based，可能为 None；对应 ruffle_core::Player::current_frame）。
int? playerCurrentFrame({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerCurrentFrame(playerId: playerId);

/// 获取当前 movie 的舞台逻辑尺寸（像素，对应 ruffle_core::Player::movie_width）。
int playerMovieWidth({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerMovieWidth(playerId: playerId);

/// 获取当前 movie 的舞台逻辑尺寸（像素，对应 ruffle_core::Player::movie_height）。
int playerMovieHeight({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerMovieHeight(playerId: playerId);

/// 获取当前 viewport 信息（物理像素 + scale_factor，对应 ruffle_core::Player::viewport_dimensions）。
ViewportDimensions playerViewportDimensions({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerViewportDimensions(
      playerId: playerId,
    );

/// 设置 player 的 viewport（width/height 为物理像素；scale_factor 通常为设备 DPR）。
void playerSetViewportDimensions({
  required BigInt playerId,
  required int width,
  required int height,
  required double scaleFactor,
}) => RustLib.instance.api.crateApiCorePlayerSetViewportDimensions(
  playerId: playerId,
  width: width,
  height: height,
  scaleFactor: scaleFactor,
);

/// 设置 player 的缩放模式（exact_fit/no_border/no_scale/show_all）。
void playerSetScaleMode({
  required BigInt playerId,
  required String scaleMode,
}) => RustLib.instance.api.crateApiCorePlayerSetScaleMode(
  playerId: playerId,
  scaleMode: scaleMode,
);

/// 获取 player 当前缩放模式（exact_fit/no_border/no_scale/show_all）。
String playerScaleMode({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerScaleMode(playerId: playerId);

/// 获取 player 是否强制缩放模式（对应 ruffle_core::Player::forced_scale_mode）。
bool playerForcedScaleMode({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerForcedScaleMode(playerId: playerId);

/// 设置是否强制缩放模式（对应 ruffle_core::Player::set_forced_scale_mode）。
void playerSetForcedScaleMode({
  required BigInt playerId,
  required bool force,
}) => RustLib.instance.api.crateApiCorePlayerSetForcedScaleMode(
  playerId: playerId,
  force: force,
);

/// 设置 player 的 window_mode（字符串：window/opaque/transparent 等；对应 ruffle_core::Player::set_window_mode）。
void playerSetWindowMode({
  required BigInt playerId,
  required String windowMode,
}) => RustLib.instance.api.crateApiCorePlayerSetWindowMode(
  playerId: playerId,
  windowMode: windowMode,
);

/// 设置是否显示右键菜单（对应 ruffle_core::Player::set_show_menu）。
void playerSetShowMenu({required BigInt playerId, required bool showMenu}) =>
    RustLib.instance.api.crateApiCorePlayerSetShowMenu(
      playerId: playerId,
      showMenu: showMenu,
    );

/// 指示 player 在下一帧后暂停（对应 ruffle_core::Player::suspend_after_next_frame）。
void playerSuspendAfterNextFrame({required BigInt playerId}) => RustLib
    .instance
    .api
    .crateApiCorePlayerSuspendAfterNextFrame(playerId: playerId);

/// 获取 player 当前鼠标是否处于舞台内（对应 ruffle_core::Player::mouse_in_stage）。
bool playerMouseInStage({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerMouseInStage(playerId: playerId);

/// 获取到下一帧的近似剩余时间（毫秒，对应 ruffle_core::Player::time_til_next_frame）。
BigInt playerTimeTilNextFrame({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerTimeTilNextFrame(playerId: playerId);

/// 向 player 注入鼠标移动事件（坐标单位为 viewport 物理像素）。
bool playerMouseMove({
  required BigInt playerId,
  required double x,
  required double y,
}) => RustLib.instance.api.crateApiCorePlayerMouseMove(
  playerId: playerId,
  x: x,
  y: y,
);

/// 向 player 注入鼠标按下事件（坐标单位为 viewport 物理像素；button: 0=Left, 1=Right, 2=Middle；index 可为空）。
bool playerMouseDown({
  required BigInt playerId,
  required double x,
  required double y,
  required int button,
  int? index,
}) => RustLib.instance.api.crateApiCorePlayerMouseDown(
  playerId: playerId,
  x: x,
  y: y,
  button: button,
  index: index,
);

/// 向 player 注入鼠标抬起事件（button: 0=Left, 1=Right, 2=Middle）。
bool playerMouseUp({
  required BigInt playerId,
  required double x,
  required double y,
  required int button,
}) => RustLib.instance.api.crateApiCorePlayerMouseUp(
  playerId: playerId,
  x: x,
  y: y,
  button: button,
);

/// 向 player 注入鼠标离开舞台事件。
bool playerMouseLeave({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerMouseLeave(playerId: playerId);

/// 设置鼠标指针是否处于舞台内（用于正确处理悬停/按钮状态/拖拽等逻辑）。
void playerSetMouseInStage({
  required BigInt playerId,
  required bool isInStage,
}) => RustLib.instance.api.crateApiCorePlayerSetMouseInStage(
  playerId: playerId,
  isInStage: isInStage,
);

/// 通知 player 获得焦点（对齐桌面端 WindowEvent::Focused(true) 行为）。
bool playerFocusGained({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerFocusGained(playerId: playerId);

/// 通知 player 失去焦点（对齐桌面端 WindowEvent::Focused(false) 行为）。
bool playerFocusLost({required BigInt playerId}) =>
    RustLib.instance.api.crateApiCorePlayerFocusLost(playerId: playerId);

/// 向 player 注入鼠标滚轮事件（delta_pixels：像素单位，正负方向与上层保持一致）。
bool playerMouseWheelPixels({
  required BigInt playerId,
  required double deltaPixels,
}) => RustLib.instance.api.crateApiCorePlayerMouseWheelPixels(
  playerId: playerId,
  deltaPixels: deltaPixels,
);

/// 向 player 注入键盘按下事件（logical_key 支持单字符或常见键名，如 ArrowLeft/Enter）。
bool playerKeyDown({required BigInt playerId, required String logicalKey}) =>
    RustLib.instance.api.crateApiCorePlayerKeyDown(
      playerId: playerId,
      logicalKey: logicalKey,
    );

/// 向 player 注入键盘抬起事件（logical_key 支持单字符或常见键名，如 ArrowLeft/Enter）。
bool playerKeyUp({required BigInt playerId, required String logicalKey}) =>
    RustLib.instance.api.crateApiCorePlayerKeyUp(
      playerId: playerId,
      logicalKey: logicalKey,
    );

/// 向 player 注入文本输入事件（单个 codepoint）。
bool playerTextInput({required BigInt playerId, required String codepoint}) =>
    RustLib.instance.api.crateApiCorePlayerTextInput(
      playerId: playerId,
      codepoint: codepoint,
    );

class ViewportDimensions {
  final int width;
  final int height;
  final double scaleFactor;

  const ViewportDimensions({
    required this.width,
    required this.height,
    required this.scaleFactor,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ scaleFactor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewportDimensions &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          scaleFactor == other.scaleFactor;
}
