// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `enter_tokio`, `get_storage_base_dir`

/// 设置 SharedObject 等落盘的基础目录（由 Flutter 的 path_provider 提供，避免权限问题）。
void setStorageBaseDir({required String path}) =>
    RustLib.instance.api.crateApiInitSetStorageBaseDir(path: path);
