// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `swf_movie_header_info`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

String version() => RustLib.instance.api.crateApiPlayerVersion();

BigInt playerCreateFromBytesPlatformSurface({
  required List<int> bytes,
  required String url,
  required BigInt surfacePtr,
  required int width,
  required int height,
  required double scaleFactor,
}) => RustLib.instance.api.crateApiPlayerPlayerCreateFromBytesPlatformSurface(
  bytes: bytes,
  url: url,
  surfacePtr: surfacePtr,
  width: width,
  height: height,
  scaleFactor: scaleFactor,
);

/// 创建离屏渲染模式的 player（用于 Windows/Linux 等没有平台 Surface 的 Flutter 端）。
BigInt playerCreateFromBytesOffscreen({
  required List<int> bytes,
  required String url,
  required int width,
  required int height,
  required double scaleFactor,
}) => RustLib.instance.api.crateApiPlayerPlayerCreateFromBytesOffscreen(
  bytes: bytes,
  url: url,
  width: width,
  height: height,
  scaleFactor: scaleFactor,
);

SwfHeaderInfo playerGetHeader({required BigInt playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerGetHeader(playerId: playerId);

int playerTotalFrames({required BigInt playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerTotalFrames(playerId: playerId);

/// 推进 player 一次，并返回本次 tick 的渲染需求/下一帧时间。
PlayerTickResult playerTick({
  required BigInt playerId,
  required double dtMillis,
}) => RustLib.instance.api.crateApiPlayerPlayerTick(
  playerId: playerId,
  dtMillis: dtMillis,
);

void playerRenderPresent({required BigInt playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerRenderPresent(playerId: playerId);

/// 将当前画面渲染到离屏纹理并抓取 RGBA 像素（宽高随当前 viewport 变化）。
RgbaFrame playerRenderCaptureRgba({required BigInt playerId}) => RustLib
    .instance
    .api
    .crateApiPlayerPlayerRenderCaptureRgba(playerId: playerId);

/// 用新的平台 surface 指针重建 wgpu surface（用于 Android 前后台或窗口重建导致的 surface 失效/变化）。
void playerRecreateSurfacePlatformSurface({
  required BigInt playerId,
  required BigInt surfacePtr,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiPlayerPlayerRecreateSurfacePlatformSurface(
  playerId: playerId,
  surfacePtr: surfacePtr,
  width: width,
  height: height,
);

bool playerDispose({required BigInt playerId}) =>
    RustLib.instance.api.crateApiPlayerPlayerDispose(playerId: playerId);

class PlayerTickResult {
  final bool needsRender;
  final BigInt timeTilNextFrameMillis;

  const PlayerTickResult({
    required this.needsRender,
    required this.timeTilNextFrameMillis,
  });

  @override
  int get hashCode => needsRender.hashCode ^ timeTilNextFrameMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerTickResult &&
          runtimeType == other.runtimeType &&
          needsRender == other.needsRender &&
          timeTilNextFrameMillis == other.timeTilNextFrameMillis;
}

class RgbaFrame {
  final int width;
  final int height;
  final Uint8List rgba;

  const RgbaFrame({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RgbaFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}

class SwfHeaderInfo {
  final int swfVersion;
  final double widthPx;
  final double heightPx;
  final double frameRate;
  final int numFrames;
  final String compression;
  final bool isActionScript3;

  const SwfHeaderInfo({
    required this.swfVersion,
    required this.widthPx,
    required this.heightPx,
    required this.frameRate,
    required this.numFrames,
    required this.compression,
    required this.isActionScript3,
  });

  @override
  int get hashCode =>
      swfVersion.hashCode ^
      widthPx.hashCode ^
      heightPx.hashCode ^
      frameRate.hashCode ^
      numFrames.hashCode ^
      compression.hashCode ^
      isActionScript3.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwfHeaderInfo &&
          runtimeType == other.runtimeType &&
          swfVersion == other.swfVersion &&
          widthPx == other.widthPx &&
          heightPx == other.heightPx &&
          frameRate == other.frameRate &&
          numFrames == other.numFrames &&
          compression == other.compression &&
          isActionScript3 == other.isActionScript3;
}
