// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/backends/navigator.dart';
import 'api/core.dart';
import 'api/init.dart';
import 'api/player.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 787502181;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ruffle',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiInitInitApp();

  List<String> crateApiBackendsNavigatorNavigatorDrainPendingExternalUrls();

  List<PendingSocketRequestInfo>
  crateApiBackendsNavigatorNavigatorDrainPendingSocketRequests();

  bool crateApiBackendsNavigatorNavigatorResolvePendingSocketRequest({
    required BigInt requestId,
    required bool allow,
  });

  int? crateApiCorePlayerBackgroundColor({required BigInt playerId});

  BigInt crateApiPlayerPlayerCreateFromBytesOffscreen({
    required List<int> bytes,
    required String url,
    required int width,
    required int height,
    required double scaleFactor,
  });

  BigInt crateApiPlayerPlayerCreateFromBytesPlatformSurface({
    required List<int> bytes,
    required String url,
    required BigInt surfacePtr,
    required int width,
    required int height,
    required double scaleFactor,
  });

  int? crateApiCorePlayerCurrentFrame({required BigInt playerId});

  bool crateApiPlayerPlayerDispose({required BigInt playerId});

  bool crateApiCorePlayerFocusGained({required BigInt playerId});

  bool crateApiCorePlayerFocusLost({required BigInt playerId});

  bool crateApiCorePlayerForcedScaleMode({required BigInt playerId});

  double crateApiCorePlayerFrameRate({required BigInt playerId});

  SwfHeaderInfo crateApiPlayerPlayerGetHeader({required BigInt playerId});

  bool crateApiCorePlayerIsFullscreen({required BigInt playerId});

  bool crateApiCorePlayerIsPlaying({required BigInt playerId});

  bool crateApiCorePlayerKeyDown({
    required BigInt playerId,
    required String logicalKey,
  });

  bool crateApiCorePlayerKeyUp({
    required BigInt playerId,
    required String logicalKey,
  });

  String crateApiCorePlayerLetterbox({required BigInt playerId});

  bool crateApiCorePlayerMouseDown({
    required BigInt playerId,
    required double x,
    required double y,
    required int button,
    int? index,
  });

  bool crateApiCorePlayerMouseInStage({required BigInt playerId});

  bool crateApiCorePlayerMouseLeave({required BigInt playerId});

  bool crateApiCorePlayerMouseMove({
    required BigInt playerId,
    required double x,
    required double y,
  });

  bool crateApiCorePlayerMouseUp({
    required BigInt playerId,
    required double x,
    required double y,
    required int button,
  });

  bool crateApiCorePlayerMouseWheelPixels({
    required BigInt playerId,
    required double deltaPixels,
  });

  int crateApiCorePlayerMovieHeight({required BigInt playerId});

  int crateApiCorePlayerMovieWidth({required BigInt playerId});

  String crateApiCorePlayerQuality({required BigInt playerId});

  void crateApiPlayerPlayerRecreateSurfacePlatformSurface({
    required BigInt playerId,
    required BigInt surfacePtr,
    required int width,
    required int height,
  });

  RgbaFrame crateApiPlayerPlayerRenderCaptureRgba({required BigInt playerId});

  void crateApiPlayerPlayerRenderPresent({required BigInt playerId});

  String crateApiCorePlayerScaleMode({required BigInt playerId});

  void crateApiCorePlayerSetAllowFullscreen({
    required BigInt playerId,
    required bool allowFullscreen,
  });

  void crateApiCorePlayerSetBackgroundColor({
    required BigInt playerId,
    int? argb,
  });

  void crateApiCorePlayerSetForcedScaleMode({
    required BigInt playerId,
    required bool force,
  });

  void crateApiCorePlayerSetFullscreen({
    required BigInt playerId,
    required bool isFullscreen,
  });

  void crateApiCorePlayerSetIsPlaying({
    required BigInt playerId,
    required bool isPlaying,
  });

  void crateApiCorePlayerSetLetterbox({
    required BigInt playerId,
    required String letterbox,
  });

  void crateApiCorePlayerSetMouseInStage({
    required BigInt playerId,
    required bool isInStage,
  });

  void crateApiCorePlayerSetQuality({
    required BigInt playerId,
    required String quality,
  });

  void crateApiCorePlayerSetScaleMode({
    required BigInt playerId,
    required String scaleMode,
  });

  void crateApiCorePlayerSetShowMenu({
    required BigInt playerId,
    required bool showMenu,
  });

  void crateApiCorePlayerSetViewportDimensions({
    required BigInt playerId,
    required int width,
    required int height,
    required double scaleFactor,
  });

  void crateApiCorePlayerSetVolume({
    required BigInt playerId,
    required double volume,
  });

  void crateApiCorePlayerSetWindowMode({
    required BigInt playerId,
    required String windowMode,
  });

  void crateApiCorePlayerSuspendAfterNextFrame({required BigInt playerId});

  bool crateApiCorePlayerTextInput({
    required BigInt playerId,
    required String codepoint,
  });

  PlayerTickResult crateApiPlayerPlayerTick({
    required BigInt playerId,
    required double dtMillis,
  });

  BigInt crateApiCorePlayerTimeTilNextFrame({required BigInt playerId});

  int crateApiPlayerPlayerTotalFrames({required BigInt playerId});

  ViewportDimensions crateApiCorePlayerViewportDimensions({
    required BigInt playerId,
  });

  double crateApiCorePlayerVolume({required BigInt playerId});

  void crateApiInitSetStorageBaseDir({required String path});

  String crateApiPlayerVersion();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<String> crateApiBackendsNavigatorNavigatorDrainPendingExternalUrls() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBackendsNavigatorNavigatorDrainPendingExternalUrlsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBackendsNavigatorNavigatorDrainPendingExternalUrlsConstMeta =>
      const TaskConstMeta(
        debugName: "navigator_drain_pending_external_urls",
        argNames: [],
      );

  @override
  List<PendingSocketRequestInfo>
  crateApiBackendsNavigatorNavigatorDrainPendingSocketRequests() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pending_socket_request_info,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBackendsNavigatorNavigatorDrainPendingSocketRequestsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBackendsNavigatorNavigatorDrainPendingSocketRequestsConstMeta =>
      const TaskConstMeta(
        debugName: "navigator_drain_pending_socket_requests",
        argNames: [],
      );

  @override
  bool crateApiBackendsNavigatorNavigatorResolvePendingSocketRequest({
    required BigInt requestId,
    required bool allow,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(requestId, serializer);
          sse_encode_bool(allow, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBackendsNavigatorNavigatorResolvePendingSocketRequestConstMeta,
        argValues: [requestId, allow],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBackendsNavigatorNavigatorResolvePendingSocketRequestConstMeta =>
      const TaskConstMeta(
        debugName: "navigator_resolve_pending_socket_request",
        argNames: ["requestId", "allow"],
      );

  @override
  int? crateApiCorePlayerBackgroundColor({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerBackgroundColorConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerBackgroundColorConstMeta =>
      const TaskConstMeta(
        debugName: "player_background_color",
        argNames: ["playerId"],
      );

  @override
  BigInt crateApiPlayerPlayerCreateFromBytesOffscreen({
    required List<int> bytes,
    required String url,
    required int width,
    required int height,
    required double scaleFactor,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(url, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_f_64(scaleFactor, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerCreateFromBytesOffscreenConstMeta,
        argValues: [bytes, url, width, height, scaleFactor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerCreateFromBytesOffscreenConstMeta =>
      const TaskConstMeta(
        debugName: "player_create_from_bytes_offscreen",
        argNames: ["bytes", "url", "width", "height", "scaleFactor"],
      );

  @override
  BigInt crateApiPlayerPlayerCreateFromBytesPlatformSurface({
    required List<int> bytes,
    required String url,
    required BigInt surfacePtr,
    required int width,
    required int height,
    required double scaleFactor,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(url, serializer);
          sse_encode_u_64(surfacePtr, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_f_64(scaleFactor, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerCreateFromBytesPlatformSurfaceConstMeta,
        argValues: [bytes, url, surfacePtr, width, height, scaleFactor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPlayerPlayerCreateFromBytesPlatformSurfaceConstMeta =>
      const TaskConstMeta(
        debugName: "player_create_from_bytes_platform_surface",
        argNames: [
          "bytes",
          "url",
          "surfacePtr",
          "width",
          "height",
          "scaleFactor",
        ],
      );

  @override
  int? crateApiCorePlayerCurrentFrame({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_16,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerCurrentFrameConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerCurrentFrameConstMeta =>
      const TaskConstMeta(
        debugName: "player_current_frame",
        argNames: ["playerId"],
      );

  @override
  bool crateApiPlayerPlayerDispose({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerPlayerDisposeConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerDisposeConstMeta =>
      const TaskConstMeta(debugName: "player_dispose", argNames: ["playerId"]);

  @override
  bool crateApiCorePlayerFocusGained({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerFocusGainedConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerFocusGainedConstMeta =>
      const TaskConstMeta(
        debugName: "player_focus_gained",
        argNames: ["playerId"],
      );

  @override
  bool crateApiCorePlayerFocusLost({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerFocusLostConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerFocusLostConstMeta =>
      const TaskConstMeta(
        debugName: "player_focus_lost",
        argNames: ["playerId"],
      );

  @override
  bool crateApiCorePlayerForcedScaleMode({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerForcedScaleModeConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerForcedScaleModeConstMeta =>
      const TaskConstMeta(
        debugName: "player_forced_scale_mode",
        argNames: ["playerId"],
      );

  @override
  double crateApiCorePlayerFrameRate({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerFrameRateConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerFrameRateConstMeta =>
      const TaskConstMeta(
        debugName: "player_frame_rate",
        argNames: ["playerId"],
      );

  @override
  SwfHeaderInfo crateApiPlayerPlayerGetHeader({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_swf_header_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerGetHeaderConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerGetHeaderConstMeta =>
      const TaskConstMeta(
        debugName: "player_get_header",
        argNames: ["playerId"],
      );

  @override
  bool crateApiCorePlayerIsFullscreen({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerIsFullscreenConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerIsFullscreenConstMeta =>
      const TaskConstMeta(
        debugName: "player_is_fullscreen",
        argNames: ["playerId"],
      );

  @override
  bool crateApiCorePlayerIsPlaying({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerIsPlayingConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerIsPlayingConstMeta =>
      const TaskConstMeta(
        debugName: "player_is_playing",
        argNames: ["playerId"],
      );

  @override
  bool crateApiCorePlayerKeyDown({
    required BigInt playerId,
    required String logicalKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_String(logicalKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerKeyDownConstMeta,
        argValues: [playerId, logicalKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerKeyDownConstMeta => const TaskConstMeta(
    debugName: "player_key_down",
    argNames: ["playerId", "logicalKey"],
  );

  @override
  bool crateApiCorePlayerKeyUp({
    required BigInt playerId,
    required String logicalKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_String(logicalKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerKeyUpConstMeta,
        argValues: [playerId, logicalKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerKeyUpConstMeta => const TaskConstMeta(
    debugName: "player_key_up",
    argNames: ["playerId", "logicalKey"],
  );

  @override
  String crateApiCorePlayerLetterbox({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerLetterboxConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerLetterboxConstMeta =>
      const TaskConstMeta(
        debugName: "player_letterbox",
        argNames: ["playerId"],
      );

  @override
  bool crateApiCorePlayerMouseDown({
    required BigInt playerId,
    required double x,
    required double y,
    required int button,
    int? index,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          sse_encode_u_8(button, serializer);
          sse_encode_opt_box_autoadd_u_32(index, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerMouseDownConstMeta,
        argValues: [playerId, x, y, button, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerMouseDownConstMeta =>
      const TaskConstMeta(
        debugName: "player_mouse_down",
        argNames: ["playerId", "x", "y", "button", "index"],
      );

  @override
  bool crateApiCorePlayerMouseInStage({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerMouseInStageConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerMouseInStageConstMeta =>
      const TaskConstMeta(
        debugName: "player_mouse_in_stage",
        argNames: ["playerId"],
      );

  @override
  bool crateApiCorePlayerMouseLeave({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerMouseLeaveConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerMouseLeaveConstMeta =>
      const TaskConstMeta(
        debugName: "player_mouse_leave",
        argNames: ["playerId"],
      );

  @override
  bool crateApiCorePlayerMouseMove({
    required BigInt playerId,
    required double x,
    required double y,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerMouseMoveConstMeta,
        argValues: [playerId, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerMouseMoveConstMeta =>
      const TaskConstMeta(
        debugName: "player_mouse_move",
        argNames: ["playerId", "x", "y"],
      );

  @override
  bool crateApiCorePlayerMouseUp({
    required BigInt playerId,
    required double x,
    required double y,
    required int button,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          sse_encode_u_8(button, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerMouseUpConstMeta,
        argValues: [playerId, x, y, button],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerMouseUpConstMeta => const TaskConstMeta(
    debugName: "player_mouse_up",
    argNames: ["playerId", "x", "y", "button"],
  );

  @override
  bool crateApiCorePlayerMouseWheelPixels({
    required BigInt playerId,
    required double deltaPixels,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_f_64(deltaPixels, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerMouseWheelPixelsConstMeta,
        argValues: [playerId, deltaPixels],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerMouseWheelPixelsConstMeta =>
      const TaskConstMeta(
        debugName: "player_mouse_wheel_pixels",
        argNames: ["playerId", "deltaPixels"],
      );

  @override
  int crateApiCorePlayerMovieHeight({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerMovieHeightConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerMovieHeightConstMeta =>
      const TaskConstMeta(
        debugName: "player_movie_height",
        argNames: ["playerId"],
      );

  @override
  int crateApiCorePlayerMovieWidth({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerMovieWidthConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerMovieWidthConstMeta =>
      const TaskConstMeta(
        debugName: "player_movie_width",
        argNames: ["playerId"],
      );

  @override
  String crateApiCorePlayerQuality({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerQualityConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerQualityConstMeta =>
      const TaskConstMeta(debugName: "player_quality", argNames: ["playerId"]);

  @override
  void crateApiPlayerPlayerRecreateSurfacePlatformSurface({
    required BigInt playerId,
    required BigInt surfacePtr,
    required int width,
    required int height,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_u_64(surfacePtr, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerRecreateSurfacePlatformSurfaceConstMeta,
        argValues: [playerId, surfacePtr, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPlayerPlayerRecreateSurfacePlatformSurfaceConstMeta =>
      const TaskConstMeta(
        debugName: "player_recreate_surface_platform_surface",
        argNames: ["playerId", "surfacePtr", "width", "height"],
      );

  @override
  RgbaFrame crateApiPlayerPlayerRenderCaptureRgba({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rgba_frame,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerRenderCaptureRgbaConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerRenderCaptureRgbaConstMeta =>
      const TaskConstMeta(
        debugName: "player_render_capture_rgba",
        argNames: ["playerId"],
      );

  @override
  void crateApiPlayerPlayerRenderPresent({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerRenderPresentConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerRenderPresentConstMeta =>
      const TaskConstMeta(
        debugName: "player_render_present",
        argNames: ["playerId"],
      );

  @override
  String crateApiCorePlayerScaleMode({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerScaleModeConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerScaleModeConstMeta =>
      const TaskConstMeta(
        debugName: "player_scale_mode",
        argNames: ["playerId"],
      );

  @override
  void crateApiCorePlayerSetAllowFullscreen({
    required BigInt playerId,
    required bool allowFullscreen,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_bool(allowFullscreen, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetAllowFullscreenConstMeta,
        argValues: [playerId, allowFullscreen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetAllowFullscreenConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_allow_fullscreen",
        argNames: ["playerId", "allowFullscreen"],
      );

  @override
  void crateApiCorePlayerSetBackgroundColor({
    required BigInt playerId,
    int? argb,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_opt_box_autoadd_u_32(argb, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetBackgroundColorConstMeta,
        argValues: [playerId, argb],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetBackgroundColorConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_background_color",
        argNames: ["playerId", "argb"],
      );

  @override
  void crateApiCorePlayerSetForcedScaleMode({
    required BigInt playerId,
    required bool force,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_bool(force, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetForcedScaleModeConstMeta,
        argValues: [playerId, force],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetForcedScaleModeConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_forced_scale_mode",
        argNames: ["playerId", "force"],
      );

  @override
  void crateApiCorePlayerSetFullscreen({
    required BigInt playerId,
    required bool isFullscreen,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_bool(isFullscreen, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetFullscreenConstMeta,
        argValues: [playerId, isFullscreen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetFullscreenConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_fullscreen",
        argNames: ["playerId", "isFullscreen"],
      );

  @override
  void crateApiCorePlayerSetIsPlaying({
    required BigInt playerId,
    required bool isPlaying,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_bool(isPlaying, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetIsPlayingConstMeta,
        argValues: [playerId, isPlaying],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetIsPlayingConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_is_playing",
        argNames: ["playerId", "isPlaying"],
      );

  @override
  void crateApiCorePlayerSetLetterbox({
    required BigInt playerId,
    required String letterbox,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_String(letterbox, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetLetterboxConstMeta,
        argValues: [playerId, letterbox],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetLetterboxConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_letterbox",
        argNames: ["playerId", "letterbox"],
      );

  @override
  void crateApiCorePlayerSetMouseInStage({
    required BigInt playerId,
    required bool isInStage,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_bool(isInStage, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetMouseInStageConstMeta,
        argValues: [playerId, isInStage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetMouseInStageConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_mouse_in_stage",
        argNames: ["playerId", "isInStage"],
      );

  @override
  void crateApiCorePlayerSetQuality({
    required BigInt playerId,
    required String quality,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_String(quality, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetQualityConstMeta,
        argValues: [playerId, quality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetQualityConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_quality",
        argNames: ["playerId", "quality"],
      );

  @override
  void crateApiCorePlayerSetScaleMode({
    required BigInt playerId,
    required String scaleMode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_String(scaleMode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 41)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetScaleModeConstMeta,
        argValues: [playerId, scaleMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetScaleModeConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_scale_mode",
        argNames: ["playerId", "scaleMode"],
      );

  @override
  void crateApiCorePlayerSetShowMenu({
    required BigInt playerId,
    required bool showMenu,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_bool(showMenu, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetShowMenuConstMeta,
        argValues: [playerId, showMenu],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetShowMenuConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_show_menu",
        argNames: ["playerId", "showMenu"],
      );

  @override
  void crateApiCorePlayerSetViewportDimensions({
    required BigInt playerId,
    required int width,
    required int height,
    required double scaleFactor,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_f_64(scaleFactor, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetViewportDimensionsConstMeta,
        argValues: [playerId, width, height, scaleFactor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetViewportDimensionsConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_viewport_dimensions",
        argNames: ["playerId", "width", "height", "scaleFactor"],
      );

  @override
  void crateApiCorePlayerSetVolume({
    required BigInt playerId,
    required double volume,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_f_32(volume, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetVolumeConstMeta,
        argValues: [playerId, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_volume",
        argNames: ["playerId", "volume"],
      );

  @override
  void crateApiCorePlayerSetWindowMode({
    required BigInt playerId,
    required String windowMode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_String(windowMode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 45)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSetWindowModeConstMeta,
        argValues: [playerId, windowMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSetWindowModeConstMeta =>
      const TaskConstMeta(
        debugName: "player_set_window_mode",
        argNames: ["playerId", "windowMode"],
      );

  @override
  void crateApiCorePlayerSuspendAfterNextFrame({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerSuspendAfterNextFrameConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerSuspendAfterNextFrameConstMeta =>
      const TaskConstMeta(
        debugName: "player_suspend_after_next_frame",
        argNames: ["playerId"],
      );

  @override
  bool crateApiCorePlayerTextInput({
    required BigInt playerId,
    required String codepoint,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_String(codepoint, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 47)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerTextInputConstMeta,
        argValues: [playerId, codepoint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerTextInputConstMeta =>
      const TaskConstMeta(
        debugName: "player_text_input",
        argNames: ["playerId", "codepoint"],
      );

  @override
  PlayerTickResult crateApiPlayerPlayerTick({
    required BigInt playerId,
    required double dtMillis,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          sse_encode_f_64(dtMillis, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 48)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_player_tick_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerTickConstMeta,
        argValues: [playerId, dtMillis],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerTickConstMeta => const TaskConstMeta(
    debugName: "player_tick",
    argNames: ["playerId", "dtMillis"],
  );

  @override
  BigInt crateApiCorePlayerTimeTilNextFrame({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 49)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerTimeTilNextFrameConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerTimeTilNextFrameConstMeta =>
      const TaskConstMeta(
        debugName: "player_time_til_next_frame",
        argNames: ["playerId"],
      );

  @override
  int crateApiPlayerPlayerTotalFrames({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 50)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerPlayerTotalFramesConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerTotalFramesConstMeta =>
      const TaskConstMeta(
        debugName: "player_total_frames",
        argNames: ["playerId"],
      );

  @override
  ViewportDimensions crateApiCorePlayerViewportDimensions({
    required BigInt playerId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 51)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_viewport_dimensions,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerViewportDimensionsConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerViewportDimensionsConstMeta =>
      const TaskConstMeta(
        debugName: "player_viewport_dimensions",
        argNames: ["playerId"],
      );

  @override
  double crateApiCorePlayerVolume({required BigInt playerId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(playerId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 52)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCorePlayerVolumeConstMeta,
        argValues: [playerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCorePlayerVolumeConstMeta =>
      const TaskConstMeta(debugName: "player_volume", argNames: ["playerId"]);

  @override
  void crateApiInitSetStorageBaseDir({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 53)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitSetStorageBaseDirConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitSetStorageBaseDirConstMeta =>
      const TaskConstMeta(
        debugName: "set_storage_base_dir",
        argNames: ["path"],
      );

  @override
  String crateApiPlayerVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 54)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerVersionConstMeta =>
      const TaskConstMeta(debugName: "version", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<PendingSocketRequestInfo> dco_decode_list_pending_socket_request_info(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_pending_socket_request_info)
        .toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PendingSocketRequestInfo dco_decode_pending_socket_request_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PendingSocketRequestInfo(
      requestId: dco_decode_u_64(arr[0]),
      host: dco_decode_String(arr[1]),
      port: dco_decode_u_16(arr[2]),
    );
  }

  @protected
  PlayerTickResult dco_decode_player_tick_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PlayerTickResult(
      needsRender: dco_decode_bool(arr[0]),
      timeTilNextFrameMillis: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  RgbaFrame dco_decode_rgba_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RgbaFrame(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      rgba: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  SwfHeaderInfo dco_decode_swf_header_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SwfHeaderInfo(
      swfVersion: dco_decode_u_8(arr[0]),
      widthPx: dco_decode_f_64(arr[1]),
      heightPx: dco_decode_f_64(arr[2]),
      frameRate: dco_decode_f_64(arr[3]),
      numFrames: dco_decode_u_16(arr[4]),
      compression: dco_decode_String(arr[5]),
      isActionScript3: dco_decode_bool(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  ViewportDimensions dco_decode_viewport_dimensions(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ViewportDimensions(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      scaleFactor: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<PendingSocketRequestInfo> sse_decode_list_pending_socket_request_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PendingSocketRequestInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pending_socket_request_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PendingSocketRequestInfo sse_decode_pending_socket_request_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_requestId = sse_decode_u_64(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    return PendingSocketRequestInfo(
      requestId: var_requestId,
      host: var_host,
      port: var_port,
    );
  }

  @protected
  PlayerTickResult sse_decode_player_tick_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_needsRender = sse_decode_bool(deserializer);
    var var_timeTilNextFrameMillis = sse_decode_u_64(deserializer);
    return PlayerTickResult(
      needsRender: var_needsRender,
      timeTilNextFrameMillis: var_timeTilNextFrameMillis,
    );
  }

  @protected
  RgbaFrame sse_decode_rgba_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return RgbaFrame(width: var_width, height: var_height, rgba: var_rgba);
  }

  @protected
  SwfHeaderInfo sse_decode_swf_header_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_swfVersion = sse_decode_u_8(deserializer);
    var var_widthPx = sse_decode_f_64(deserializer);
    var var_heightPx = sse_decode_f_64(deserializer);
    var var_frameRate = sse_decode_f_64(deserializer);
    var var_numFrames = sse_decode_u_16(deserializer);
    var var_compression = sse_decode_String(deserializer);
    var var_isActionScript3 = sse_decode_bool(deserializer);
    return SwfHeaderInfo(
      swfVersion: var_swfVersion,
      widthPx: var_widthPx,
      heightPx: var_heightPx,
      frameRate: var_frameRate,
      numFrames: var_numFrames,
      compression: var_compression,
      isActionScript3: var_isActionScript3,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  ViewportDimensions sse_decode_viewport_dimensions(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_scaleFactor = sse_decode_f_64(deserializer);
    return ViewportDimensions(
      width: var_width,
      height: var_height,
      scaleFactor: var_scaleFactor,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pending_socket_request_info(
    List<PendingSocketRequestInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pending_socket_request_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_pending_socket_request_info(
    PendingSocketRequestInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.requestId, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
  }

  @protected
  void sse_encode_player_tick_result(
    PlayerTickResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.needsRender, serializer);
    sse_encode_u_64(self.timeTilNextFrameMillis, serializer);
  }

  @protected
  void sse_encode_rgba_frame(RgbaFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }

  @protected
  void sse_encode_swf_header_info(
    SwfHeaderInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.swfVersion, serializer);
    sse_encode_f_64(self.widthPx, serializer);
    sse_encode_f_64(self.heightPx, serializer);
    sse_encode_f_64(self.frameRate, serializer);
    sse_encode_u_16(self.numFrames, serializer);
    sse_encode_String(self.compression, serializer);
    sse_encode_bool(self.isActionScript3, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_viewport_dimensions(
    ViewportDimensions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_f_64(self.scaleFactor, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
