// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 取出（并清空）等待处理的外部链接打开请求。
List<String> navigatorDrainPendingExternalUrls() => RustLib.instance.api
    .crateApiBackendsNavigatorNavigatorDrainPendingExternalUrls();

/// 取出（并清空）等待处理的 Socket 连接确认请求。
List<PendingSocketRequestInfo> navigatorDrainPendingSocketRequests() => RustLib
    .instance
    .api
    .crateApiBackendsNavigatorNavigatorDrainPendingSocketRequests();

/// 对指定的 Socket 连接确认请求进行应答（allow/deny），并返回是否成功找到该请求。
bool navigatorResolvePendingSocketRequest({
  required BigInt requestId,
  required bool allow,
}) => RustLib.instance.api
    .crateApiBackendsNavigatorNavigatorResolvePendingSocketRequest(
      requestId: requestId,
      allow: allow,
    );

class PendingSocketRequestInfo {
  final BigInt requestId;
  final String host;
  final int port;

  const PendingSocketRequestInfo({
    required this.requestId,
    required this.host,
    required this.port,
  });

  @override
  int get hashCode => requestId.hashCode ^ host.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingSocketRequestInfo &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          host == other.host &&
          port == other.port;
}
